### ISSUE TITLE
I cannot find any place to download this extension

### ISSUE THREAD

**Issue by alvinlee001** [artemkaxboy/jib-custom-entrypoint-extension#3]
Hi @artemkaxboy , could this extension be used by downloading from maven? May i know how I am able to use this?

**Comment by artemkaxboy** [comment]
Extensions are available on mvn central (https://mvnrepository.com/artifact/com.artemkaxboy)

You can find usage examples here: [maven](https://github.com/artemkaxboy/jib-custom-entrypoint-extension/blob/9963627ebd767591c6e8710e894b1db25b1cb7e1/sample-maven-java/pom.xml#L71), [gradle](https://github.com/artemkaxboy/jib-custom-entrypoint-extension/blob/9963627ebd767591c6e8710e894b1db25b1cb7e1/sample-gradle-java/build.gradle#L59)
